[[constraint]]
  name = "github.com/brigadecore/brigade"
  revision = "509b6edd37222cade4b3970554088b2046b46a44"

[[constraint]]
  name = "github.com/google/go-github"
  version = "v18.2.0"

[[constraint]]
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "gopkg.in/gin-gonic/gin.v1"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.10"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true
